[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
rusqlite = { version = "0.35.0", features = ["bundled", "time"] }
termcolor = "1.4.1"
time = { version = "0.3.41", features = ["parsing", "local-offset"] }
